version: '3.7'

services:
  web-server:
    image: nginx:1.21
    container_name: web-server
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/conf:/etc/nginx/conf.d:ro
      - ./magento_ecommerce:/var/www/html

  phpfpm:
    env_file: .env
    build:
      context: ./docker/phpfpm
      args:
        - UID=${UID}
        - GID=${GID}
    container_name: phpfpm
    volumes:
      - ./magento_ecommerce:/var/www/html
      - ./scripts:/scripts
    # command: bash /scripts/install.sh

  elasticsearch:
    ports:
    - "9200:9200"
    - "9300:9300"
    # original: https://github.com/markshust/docker-magento/blob/master/compose/docker-compose.yml
    image: markoshust/magento-elasticsearch:7.9.3-1
    environment:
      - "discovery.type=single-node"
      ## Set custom heap size to avoid memory errors
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      ## Avoid test failures due to small disks
      ## More info at https://github.com/markshust/docker-magento/issues/488
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"
