# Custom docker-compose to speed up ci (github action)
version: "3.8"

services:
  phpfpm:
    environment:
      - MYSQL_HOST=127.0.0.1
      - ELASTICSEARCH_HOST=127.0.0.1
    volumes:
      - ./cache/composer:/var/www/.composer/cache
    network_mode: host
