# Custom docker-compose to speed up ci (github action)
version: "3.8"

services:
  phpfpm:
    volumes:
      - ./cache/composer:/var/www/.composer/cache
      - ./credentials/auth.json:/var/www/html/auth.json
    extra_hosts:
    - "host.docker.internal:host-gateway"
    network_mode: host
