# Custom docker-compose to speed up ci (github action)
version: "3.8"

services:
  phpfpm:
    environment:
      - MYSQL_HOST=host.docker.internal
    volumes:
      - ./cache/composer:/var/www/.composer/cache
    extra_hosts:
        - "host.docker.internal:host-gateway"