<?php
/** @var Currency $block */

use Dabilo\MiniWindow\Block\Widget\Currency;

?>
<?php
$result = $block->getCurrencyInformation();
$data = simplexml_load_string($result);
$time = $data->DateTime;
$rate = $data->Exrate;

?>

<?php if($block->getData('currency')): ?>
    <h2 class='currency'><b><?php echo $block->getData('currency'); ?></b>
    </h2>
    <table class='currency_table'>
        <tr>
            <th>Code</th>
            <th>Currency Name</th>
            <th>Buy</th>
            <th>Transfer</th>
            <th>Sell</th>
        </tr>
        <?php
        foreach($rate as $currency) {
            $code = $currency['CurrencyCode'];
            $name = $currency['CurrencyName'];
            $buy = $currency['Buy'];
            $transfer = $currency['Transfer'];
            $sell = $currency['Sell']; ?>
            <tr>
                <td><?php echo $code?></td>
                <td><?php echo $name?></td>
                <td><?php echo $buy?></td>
                <td><?php echo $transfer?></td>
                <td><?php echo $sell?></td>
            </tr>
            <?php
        } ?>
    </table>
<?php endif; ?>

<style>
.currency_table{
  border-collapse: collapse;
}
.currency_table th, td {
  text-align: left;
  padding: 8px;
}
.currency_table tr:nth-child(even) {background-color: #f2f2f2;}
</style>