<?php
/** @var Weather $block */

use Hanna\MiniWindow\Block\Widget\Weather;

?>
<?php
$result = $block->getWeatherInformation();
$main = $result->weather[0]['main'];
$description = $result->weather[0]['description'];
$temp = $result->main['temp'] - 273;
$temp_min = $result->main['temp_min'] - 273;
$temp_max = $result->main['temp_max'] - 273;
$humid = $result->main['humidity'];
date_default_timezone_set('Asia/Ho_Chi_Minh');
$currentTime = time();
?>

<?php if($block->getData('current_weather')): ?>
    <h2 class='current_weather'><b><?php echo $block->getData('current_weather'); ?></b>
    </h2>
      <div class="report-container">
        <h3><?php echo "Hanoi";?></h3>
        <div class="time">
            <div><?php echo date("l g:i a", $currentTime); ?></div>
            <div><?php echo date("jS F, Y",$currentTime); ?></div>
            <div><?php echo ucwords($description); ?></div>
        </div>
        <div class="weather-forecast">
            <img
                src="http://openweathermap.org/img/w/<?php echo $result->weather[0]['icon']; ?>.png"
                class="weather-icon" /> <?php echo $temp_max; ?>°C<span
                class="min-temperature"><?php echo $temp_min; ?>°C</span>
        </div>
        <div class="time">
            <div>Humidity: <?php echo $humid; ?> %</div>
            <div>Wind: <?php echo $result->wind['speed']; ?> km/h</div>
        </div>
    </div>

    
<?php endif; ?>

<style>
.report-container {
    border: #E0E0E0 1px solid;
    padding: 20px 40px 40px 40px;
    border-radius: 2px;
    width: 550px;
    margin: 0 auto;
}

.weather-icon {
    vertical-align: middle;
    margin-right: 20px;
}

.weather-forecast {
    color: #212121;
    font-size: 1.2em;
    font-weight: bold;
    margin: 20px 0px;
}

span.min-temperature {
    margin-left: 15px;
    color: #929292;
}

.time {
    line-height: 25px;
}
</style>