name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v2
    - name: Try to run docker compose
      env:
       PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
       PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: make init
