name: Test Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v2
    - name: set auth_env
      env:
        PUBLIC_KEY: ${{secrets.PUBLIC_KEY}}
        PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
      run: make prepare
    - run: docker-compose pull
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: Run docker compose
      run: make install
