name: Docker Compose CI2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v2
    - run: docker-compose pull
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: Run docker compose
      env:
       COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
      run: make init
