name: build docker compose

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v2

      - name: prepare
        env:
          PUBLIC_KEY: ${{secrets.PUBLIC_KEY}}
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
        run: |
          mkdir -p cache/composer cache/vendor
          make prepare

      - run: docker-compose pull

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          concurrency: true
          key: k0-docker-cache-{hash}
          restore-keys: k0-docker-cache-

      - uses: actions/cache@v2
        env:
          cache-ver: v01
        with:
          path: ./cache
          key: ${{ runner.os }}-${{ env.cache-ver }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-ver }}-

      - name: install
        run: |
          docker-compose -f docker-compose.yaml -f docker-compose.ci.yaml up -d
          docker exec $(fpm-container-name) sh /scripts/install.sh
