name: build docker compose

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v2

      - name: prepare
        env:
          PUBLIC_KEY: ${{secrets.PUBLIC_KEY}}
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
        run: |
          mkdir -p cache/composer
          make prepare

      - name: create database with sql file
        run: |
          sudo systemctl start mysql.service
          mysql -h 127.0.0.1 -uroot -proot -e "CREATE USER 'magento'@'%' IDENTIFIED BY 'magento';"
          mysql -h 127.0.0.1 -uroot -proot -e "CREATE DATABASE ecom;"
          mysql -h 127.0.0.1 -uroot -proot -e "GRANT ALL ON ecom.* TO 'magento'@'%';"
          mysql -h 127.0.0.1 -umagento -pmagento ecom < ./initdb/01.schema.sql
          mysql -h 127.0.0.1 -umagento -pmagento ecom < ./initdb/02.data.sql

      - run: docker-compose -f docker-compose.yaml pull

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          concurrency: true
          key: docker-cache-${{ hashFiles('**/docker-compose.*', '**/Dockerfile') }}-{hash}
          restore-keys: docker-cache-${{ hashFiles('**/docker-compose.*', '**/Dockerfile') }}

      - name: cache composer registry
        uses: actions/cache@v2
        env:
          cache-name: composer-registry-v01
        with:
          path: ./cache/composer
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-

      - name: cache composer build
        uses: actions/cache@v2
        env:
          cache-name: composer-build-v01
        with:
          path: ./magento_ecommerce/vendor
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-

      - name: compose up
        run: docker-compose -f docker-compose.yaml -f docker/docker-compose.ci.yaml up -d
      
      - name: docker-compose logs
        run: |
          docker ps -a
          docker-compose logs phpfpm
          docker-compose logs web-server

      - name: basic test
        run: |
          bash ./scripts/wait-for-it.sh localhost:8080 -t 0
          curl localhost:8080