name: build docker compose

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v2

      - name: prepare
        env:
          PUBLIC_KEY: ${{secrets.PUBLIC_KEY}}
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
        run: |
          mkdir -p cache/composer
          make prepare

      - name: create database with sql file
        run: |
          sudo systemctl start mysql.service
          mysql -h 127.0.0.1 -uroot -proot -e "CREATE USER 'magento'@'%' IDENTIFIED BY 'magento';"
          mysql -h 127.0.0.1 -uroot -proot -e "CREATE DATABASE magento_db;"
          mysql -h 127.0.0.1 -uroot -proot -e "GRANT ALL ON magento_db.* TO 'magento'@'%';"

      - run: docker-compose -f docker-compose.yaml pull

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          concurrency: true
          key: k2-docker-cache-{hash}
          restore-keys: k2-docker-cache-

      - name: cache composer registry
        uses: actions/cache@v2
        env:
          cache-name: composer-registry-v01
        with:
          path: ./cache/composer
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-

      - name: cache composer build
        uses: actions/cache@v2
        env:
          cache-name: composer-build-v01
        with:
          path: ./magento_ecommerce/vendor
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-

      - name: compose up
        run: docker-compose -f docker-compose.yaml -f docker/docker-compose.ci.yaml up -d
